application: mini-cloud-scheduler
runtime: python27
version: 1
api_version: 1
threadsafe: true
automatic_scaling:
  max_idle_instances: 3

handlers:

- url: /.*
  script: main.app

- url: /static
  static_dir: static
  application_readable: true

- url: /favicon.ico
  static_files: /static/favicon.ico
  upload: /static/favicon.ico


builtins:
- deferred: on

libraries:
- name: webapp2
  version: latest
- name: flask
  version: latest
- name: ssl
  version: latest

resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10

